--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\generic\wrapperFunction.py", line 96, in is_element_visible
    self.set_highlighter(webelement)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\generic\wrapperFunction.py", line 144, in set_highlighter
    self.driver.execute_script("arguments[0].setAttribute('style', arguments[1]);", element)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=126.0.6478.128); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF63D9DEEB2+31554]
	(No symbol) [0x00007FF63D957EE9]
	(No symbol) [0x00007FF63D81872A]
	(No symbol) [0x00007FF63D81E55E]
	(No symbol) [0x00007FF63D8211D8]
	(No symbol) [0x00007FF63D8AD69B]
	(No symbol) [0x00007FF63D88D02A]
	(No symbol) [0x00007FF63D8AC977]
	(No symbol) [0x00007FF63D88CDD3]
	(No symbol) [0x00007FF63D85A33B]
	(No symbol) [0x00007FF63D85AED1]
	GetHandleVerifier [0x00007FF63DCE8B2D+3217341]
	GetHandleVerifier [0x00007FF63DD35AF3+3532675]
	GetHandleVerifier [0x00007FF63DD2B0F0+3489152]
	GetHandleVerifier [0x00007FF63DA8E786+750614]
	(No symbol) [0x00007FF63D96376F]
	(No symbol) [0x00007FF63D95EB24]
	(No symbol) [0x00007FF63D95ECB2]
	(No symbol) [0x00007FF63D94E17F]
	BaseThreadInitThunk [0x00007FFEE71C257D+29]
	RtlUserThreadStart [0x00007FFEE8ECAF28+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\.venv\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\config\__init__.py", line 206, in console_main
    code = main()
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\config\__init__.py", line 178, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\main.py", line 332, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\main.py", line 285, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\main.py", line 339, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\main.py", line 364, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 116, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 135, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 240, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 241, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 173, in pytest_runtest_call
    item.runtest()
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\python.py", line 162, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\testCases\DemoBlazeEndToEndFlow_Test.py", line 66, in test_TCID_103_Verify_product_category_functionality
    home_page.verify_products_are_visible(test_data["mob_product_1"], test_data["mob_product_2"],
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\allure_commons\_allure.py", line 192, in impl
    return func(*a, **kw)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\pageFactory\homePage.py", line 43, in verify_products_are_visible
    self.is_element_visible((By.XPATH, f"//a[contains(.,'{product}')]"))
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\generic\wrapperFunction.py", line 99, in is_element_visible
    TestUtil.logger.log(logging.INFO, "erro", error)
Message: 'erro'
Arguments: (StaleElementReferenceException(),)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\generic\wrapperFunction.py", line 96, in is_element_visible
    self.set_highlighter(webelement)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\generic\wrapperFunction.py", line 144, in set_highlighter
    self.driver.execute_script("arguments[0].setAttribute('style', arguments[1]);", element)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=126.0.6478.128); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF63D9DEEB2+31554]
	(No symbol) [0x00007FF63D957EE9]
	(No symbol) [0x00007FF63D81872A]
	(No symbol) [0x00007FF63D81E55E]
	(No symbol) [0x00007FF63D8211D8]
	(No symbol) [0x00007FF63D8AD69B]
	(No symbol) [0x00007FF63D88D02A]
	(No symbol) [0x00007FF63D8AC977]
	(No symbol) [0x00007FF63D88CDD3]
	(No symbol) [0x00007FF63D85A33B]
	(No symbol) [0x00007FF63D85AED1]
	GetHandleVerifier [0x00007FF63DCE8B2D+3217341]
	GetHandleVerifier [0x00007FF63DD35AF3+3532675]
	GetHandleVerifier [0x00007FF63DD2B0F0+3489152]
	GetHandleVerifier [0x00007FF63DA8E786+750614]
	(No symbol) [0x00007FF63D96376F]
	(No symbol) [0x00007FF63D95EB24]
	(No symbol) [0x00007FF63D95ECB2]
	(No symbol) [0x00007FF63D94E17F]
	BaseThreadInitThunk [0x00007FFEE71C257D+29]
	RtlUserThreadStart [0x00007FFEE8ECAF28+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\.venv\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\config\__init__.py", line 206, in console_main
    code = main()
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\config\__init__.py", line 178, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\main.py", line 332, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\main.py", line 285, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\main.py", line 339, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\main.py", line 364, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 116, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 135, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 240, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 241, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\runner.py", line 173, in pytest_runtest_call
    item.runtest()
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\_pytest\python.py", line 162, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\testCases\DemoBlazeEndToEndFlow_Test.py", line 66, in test_TCID_103_Verify_product_category_functionality
    home_page.verify_products_are_visible(test_data["mob_product_1"], test_data["mob_product_2"],
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlazeProject\.venv\Lib\site-packages\allure_commons\_allure.py", line 192, in impl
    return func(*a, **kw)
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\pageFactory\homePage.py", line 43, in verify_products_are_visible
    self.is_element_visible((By.XPATH, f"//a[contains(.,'{product}')]"))
  File "C:\Users\hp\Desktop\prashant\Projects\DemoBlaze-TAF\generic\wrapperFunction.py", line 99, in is_element_visible
    TestUtil.logger.log(logging.INFO, "erro", error)
Message: 'erro'
Arguments: (StaleElementReferenceException(),)
